POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "gaby@email.com",
    "name": "Gabriele" ,
    "password": "gaby123",
    "role": "usuario"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "miguel@miguel.com",
    "password": "admin"
}

###
 POST http://localhost:3000/band/insert
 Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyYWFhNTliLWUxMDEtNGRlZC04Y2FiLThjMWYzODY2YWE3YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MjU5NjA3NywiZXhwIjoxNjYyNjE0MDc3fQ.rPV2Pke44a5Dp62j_q-OMK4FbevVuCmuecNIFuhpoUI
 Content-Type: application/json

 {
    "name": "MixTape",
    "music_genre": "Eletrônica",
    "responsible": "Dj Guh"
 }

###
 GET http://localhost:3000/band/4e0c4e76-4ac5-4142-b14c-0654aa50fb56

###