//Endpoints de Usuários

POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "gaby@email.com",
    "name": "Gabriele" ,
    "password": "gaby123",
    "role": "usuario"
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "miguel@miguel.com",
    "password": "admin"
}

//Endpoints de Bandas

###
 POST http://localhost:3000/band/insert
 Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE4N2U4YWY1LWZhYmYtNGI2MC1hY2E4LTkwYmE3MzVmZDcwZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2Mjc3NzI4NCwiZXhwIjoxNjYyNzk1Mjg0fQ.kLmxWW_TuPYeHoa18HJxGWdUbzzlXoOFfG1_0RlPbzU
 Content-Type: application/json

 {
    "name": "MixTape",
    "music_genre": "Eletrônica",
    "responsible": "Dj Guh"
 }

###
 GET http://localhost:3000/band/4e0c4e76-4ac5-4142-b14c-0654aa50fb56

###

// Endpoints de Shows

POST http://localhost:3000/show/insert
 Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE4N2U4YWY1LWZhYmYtNGI2MC1hY2E4LTkwYmE3MzVmZDcwZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2Mjc3NzI4NCwiZXhwIjoxNjYyNzk1Mjg0fQ.kLmxWW_TuPYeHoa18HJxGWdUbzzlXoOFfG1_0RlPbzU
 Content-Type: application/json

 {
    "week_day": "sabado",
    "start_time": 14,
    "end_time": 16,
    "band_id": "4e0c4e76-4ac5-4142-b14c-0654aa50fb56"
 }

 ###